-- Limit:
SELECT * FROM people 
ORDER BY pid LIMIT 10 OFFSET 0;

SELECT * FROM people 
ORDER BY pid LIMIT 10 OFFSET 10;

SELECT * FROM people 
ORDER BY pid LIMIT 10 OFFSET 20;

SELECT * FROM people 
ORDER BY pid LIMIT 10 OFFSET 30;